title: Redmine Brasil
description: My Personal Blog
author: Patrick Kaminski
logo: 
github: https://github.com/RedmineBR
about: 

baseurl: "https://redminebr.github.io"
url: "https://redminebr.github.io"

allowsearch: false

disqus_shortname: 
google_analytics: 

share:
  twitter_username: patrixsbs
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
